stages:
  generate_data:
    cmd: python3 dvc_sample_project/data/generate_data.py
    deps:
    - dvc_sample_project/data/generate_data.py
    params:
    - data.n_objects
    outs:
    - data/raw/data.csv
  split_data:
    cmd: python3 dvc_sample_project/features/split_data.py
    deps:
    - data/raw/data.csv
    - dvc_sample_project/features/split_data.py
    params:
    - split.random_state
    - split.test_size
    outs:
    - data/processed/test.csv
    - data/processed/train.csv
  train_catboost:
    cmd: python3 dvc_sample_project/trainers/train_catboost.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - dvc_sample_project/trainers/train_catboost.py
    params:
    - catboost
    outs:
    - artifacts/catboost.pkl:
        checkpoint: true
    live:
      logs:
        summary: true
        html: false
