name: assign_issues_and_pulls_to_project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_issues_and_pulls_to_project:
    runs-on: ubuntu-latest
    steps:
    - uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/konodyuk/dvc-sample-project/projects/1'
